/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MorService } from "../mor.service";
import { MorCreateInput } from "./MorCreateInput";
import { Mor } from "./Mor";
import { MorFindManyArgs } from "./MorFindManyArgs";
import { MorWhereUniqueInput } from "./MorWhereUniqueInput";
import { MorUpdateInput } from "./MorUpdateInput";

export class MorControllerBase {
  constructor(protected readonly service: MorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mor })
  async createMor(@common.Body() data: MorCreateInput): Promise<Mor> {
    return await this.service.createMor({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mor] })
  @ApiNestedQuery(MorFindManyArgs)
  async mors(@common.Req() request: Request): Promise<Mor[]> {
    const args = plainToClass(MorFindManyArgs, request.query);
    return this.service.mors({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mor(@common.Param() params: MorWhereUniqueInput): Promise<Mor | null> {
    const result = await this.service.mor({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMor(
    @common.Param() params: MorWhereUniqueInput,
    @common.Body() data: MorUpdateInput
  ): Promise<Mor | null> {
    try {
      return await this.service.updateMor({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMor(
    @common.Param() params: MorWhereUniqueInput
  ): Promise<Mor | null> {
    try {
      return await this.service.deleteMor({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
